#!/bin/bash

ROOT=`dirname $0`
if [[ -z "$GRADLEW_NAME" ]]
then
    GRADLEW_NAME="gradlew"
fi

if [[ -z "$GRADLEW" ]]
then
    GRADLEW=${ROOT}/$GRADLEW_NAME
fi

ARGUMENTS="$*"

#${GRADLEW} run --args="$*" -x slc-sherrloc --quiet 2> /dev/null
${GRADLEW} run -x test --args="$*" 
