#!/bin/bash

ROOT=`dirname $0`

export GRADLE_OPTS="${GRADLE_OPTS} --enable-native-access=ALL-UNNAMED"

if [[ -z "$GRADLE" ]]
then
    GRADLE=${ROOT}/gradlew
fi

ARGUMENTS="$*"

#${GRADLEW} run --args="$*" -x slc-sherrloc --quiet 2> /dev/null

if [[ -n "$ARGUMENTS" ]]
then
    # ${GRADLE} run -x test --args=\""$*"\"
    ${GRADLE} run -x test --args="$*"
else
    ${GRADLE} run -x test
fi
