#!/bin/bash

ROOT=`dirname $0`
GRADLEW_NAME="gradlew"
GRADLEW=${ROOT}/$GRADLEW_NAME
ARGUMENTS="$*"
#echo $ARGUMENTS
#${GRADLEW} run --args="$*" -x slc-sherrloc --quiet 2> /dev/null
${GRADLEW} run -x test --args="$*" 

# echo ${COMMAND}

#${COMMAND}
