
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 64;
  public static final int AS = 11;
  public static final int FROM = 25;
  public static final int DOUBLESTAREQUAL = 85;
  public static final int PERCENTEQUAL = 79;
  public static final int RSQB = 45;
  public static final int NEWLINE = 88;
  public static final int ASYNC = 13;
  public static final int RAISE = 36;
  public static final int NONLOCAL = 32;
  public static final int SEMI = 48;
  public static final int LAMBDA = 31;
  public static final int RIGHTSHIFT = 70;
  public static final int NAME = 8;
  public static final int PASS = 35;
  public static final int INDENT = 89;
  public static final int COMMA = 47;
  public static final int DEDENT = 90;
  public static final int RBRACE = 61;
  public static final int VBAR = 53;
  public static final int ELIF = 20;
  public static final int LBRACE = 60;
  public static final int PLUSEQUAL = 71;
  public static final int DEL = 19;
  public static final int YIELD = 41;
  public static final int FALSE = 5;
  public static final int NOT = 33;
  public static final int TILDE = 63;
  public static final int DEF = 18;
  public static final int DOUBLESTAR = 74;
  public static final int ERROR = 2;
  public static final int CLASS = 16;
  public static final int EXCEPT = 22;
  public static final int NUMBER = 3;
  public static final int UPLUS = 91;
  public static final int SLASH = 52;
  public static final int TRUE = 6;
  public static final int LESSEQUAL = 67;
  public static final int PLUS = 49;
  public static final int PERCENT = 59;
  public static final int LPAR = 42;
  public static final int WHILE = 39;
  public static final int GREATEREQUAL = 69;
  public static final int EQUAL = 57;
  public static final int DOUBLESLASHEQUAL = 86;
  public static final int UTILDE = 93;
  public static final int NONE = 7;
  public static final int CIRCUMFLEX = 62;
  public static final int LEFTSHIFT = 68;
  public static final int FOR = 24;
  public static final int STAR = 51;
  public static final int GREATER = 56;
  public static final int RETURN = 37;
  public static final int RIGHTSHIFTEQUAL = 84;
  public static final int ELSE = 21;
  public static final int TRY = 38;
  public static final int BREAK = 15;
  public static final int DOT = 58;
  public static final int INT = 87;
  public static final int MINEQUAL = 72;
  public static final int AMPER = 54;
  public static final int EOF = 0;
  public static final int RPAR = 43;
  public static final int AWAIT = 14;
  public static final int IMPORT = 28;
  public static final int IS = 30;
  public static final int MINUS = 50;
  public static final int IN = 29;
  public static final int OR = 34;
  public static final int error = 1;
  public static final int CIRCUMFLEXEQUAL = 81;
  public static final int VBAREQUAL = 78;
  public static final int FINALLY = 23;
  public static final int CONTINUE = 17;
  public static final int SLASHEQUAL = 77;
  public static final int STAREQUAL = 75;
  public static final int IF = 27;
  public static final int RARROW = 73;
  public static final int COLON = 46;
  public static final int ASSERT = 12;
  public static final int AMPEREQUAL = 80;
  public static final int LEFTSHIFTEQUAL = 83;
  public static final int EQEQUAL = 65;
  public static final int GLOBAL = 26;
  public static final int NOTEQUAL = 66;
  public static final int LSQB = 44;
  public static final int STRING = 4;
  public static final int DOUBLESLASH = 76;
  public static final int LESS = 55;
  public static final int AND = 10;
  public static final int UMINUS = 92;
  public static final int ELLIPSIS = 9;
  public static final int ATEQUAL = 82;
  public static final int WITH = 40;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "NUMBER",
  "STRING",
  "FALSE",
  "TRUE",
  "NONE",
  "NAME",
  "ELLIPSIS",
  "AND",
  "AS",
  "ASSERT",
  "ASYNC",
  "AWAIT",
  "BREAK",
  "CLASS",
  "CONTINUE",
  "DEF",
  "DEL",
  "ELIF",
  "ELSE",
  "EXCEPT",
  "FINALLY",
  "FOR",
  "FROM",
  "GLOBAL",
  "IF",
  "IMPORT",
  "IN",
  "IS",
  "LAMBDA",
  "NONLOCAL",
  "NOT",
  "OR",
  "PASS",
  "RAISE",
  "RETURN",
  "TRY",
  "WHILE",
  "WITH",
  "YIELD",
  "LPAR",
  "RPAR",
  "LSQB",
  "RSQB",
  "COLON",
  "COMMA",
  "SEMI",
  "PLUS",
  "MINUS",
  "STAR",
  "SLASH",
  "VBAR",
  "AMPER",
  "LESS",
  "GREATER",
  "EQUAL",
  "DOT",
  "PERCENT",
  "LBRACE",
  "RBRACE",
  "CIRCUMFLEX",
  "TILDE",
  "AT",
  "EQEQUAL",
  "NOTEQUAL",
  "LESSEQUAL",
  "LEFTSHIFT",
  "GREATEREQUAL",
  "RIGHTSHIFT",
  "PLUSEQUAL",
  "MINEQUAL",
  "RARROW",
  "DOUBLESTAR",
  "STAREQUAL",
  "DOUBLESLASH",
  "SLASHEQUAL",
  "VBAREQUAL",
  "PERCENTEQUAL",
  "AMPEREQUAL",
  "CIRCUMFLEXEQUAL",
  "ATEQUAL",
  "LEFTSHIFTEQUAL",
  "RIGHTSHIFTEQUAL",
  "DOUBLESTAREQUAL",
  "DOUBLESLASHEQUAL",
  "INT",
  "NEWLINE",
  "INDENT",
  "DEDENT",
  "UPLUS",
  "UMINUS",
  "UTILDE"
  };
}

